language: ruby
rvm:
  - 2.5.3
addons:
  apt:
    # update the list above if more deps are introduced
    packages:
    - gcc
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev
    - libc6-dbg
    - valgrind
before_script:
  - export ROOT_PATH=`pwd`

  # 获取当前稳定版本号
  - wget http://nim-lang.org/channels/stable -O version.txt
  - export VERSION=`cat version.txt`

  # 安装 Nim 
  - wget https://nim-lang.org/download/nim-${VERSION}-linux_x64.tar.xz
  - tar Jxvf nim-${VERSION}-linux_x64.tar.xz
  - cd nim-${VERSION}/doc/html
  - export DOC_PATH=`pwd`
  - export NIM=`pwd`/../../bin
  - export NIMBLE_DIR=/home/travis/.nimble
  - export PATH=$PATH:$NIM:$NIMBLE
  
  # 将已翻译好的文档rst复制过来
  - cp -rf ${ROOT_PATH}/rst/* ${DOC_PATH}/../

  - gem install bundler
#   - gem install jekyll-sitemap
#   - gem install kramdown-parser-gfm
script:
  - cd ${ROOT_PATH}/jekyll
  - bundle exec jekyll build
after_success:
  - cd ${ROOT_PATH}/jekyll/_site

  - echo ${VERSION} > version.txt
  
  # 绑定域名
  - echo "nim-lang-cn.org" > CNAME

  # 创建 choosenim 的安装脚本
  - mkdir docs choosenim
  - cd choosenim/ && wget https://nim-lang.org/choosenim/init.sh 

  # 生成文档、教程、手册 
  - cd ${DOC_PATH}/../../
  - chmod a+x koch
  - ./koch docs
  
  - cp -rf ${DOC_PATH}/../../web/upload/${VERSION}/* ${ROOT_PATH}/jekyll/_site/docs/

  # 更新到 GitHub 上的 nim-lang-cn/website 的 gh-pages 分支
  - cd /home/travis/build/nim-lang-cn/website/jekyll/_site

  - git init

  - git config user.name "DongyunLee"
  - git config user.email "dongyunli619@gmail.com"

  - git add .
  - git commit -m "Update"
  
  - git push --force --quiet "https://${GH_TOKEN}@github.com/nim-lang-cn/website.git" master:gh-pages
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache:
  - bundler # caching bundler gem packages will speed up build
