language: ruby
rvm:
  - 2.7.0
script:
  - gem install bundler
  - bundle exec jekyll build
after_success:
  - cd ./jekyll/_site
  - git init
  - git config user.name "DongyunLee"
  - git config user.email "dongyunli619@gmail.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/nim-lang-cn/website.git" gh-pages:gh-pages
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
exclude: [vendor]
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build
