language: ruby
rvm:
  - 2.5.3
before_script:
  - chmod +x ./script/install_nim.sh
  - ./script/install_nim.sh
  - gem install bundler
script:
  - cd ../jekyll
  - bundle exec jekyll build
after_success:
  - chmod +x ./script/publish_gh-pages.sh
  - ./script/publish_gh-pages.sh
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
exclude: [vendor,Nim]
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: true # route your build to the container-based infrastructure for a faster build

cache: 
  - bundler # caching bundler gem packages will speed up build
