language: ruby
rvm:
  - 2.5.3
before_script:
#  - git clone https://github.com/nim-lang/Nim.git
  - cd Nim
#  - sh build_all.sh
  - echo "export NIM=/root/Nim/bin"  >> ~/.bashrc
  - echo "export NIMBLE_DIR=/root/.nimble"  >> ~/.bashrc
  - echo "export PATH=$PATH:$NIM:$NIMBLE"  >> ~/.bashrc
  - source ~/.bashrc  - gem install bundler
script:
  - cd ../jekyll
  - bundle exec jekyll build
after_success:
  - cd ./_site
  - git init
  - git config user.name "DongyunLee"
  - git config user.email "dongyunli619@gmail.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/nim-lang-cn/website.git" master:gh-pages
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
exclude: [vendor,Nim]
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: true # route your build to the container-based infrastructure for a faster build

cache: 
  - bundler # caching bundler gem packages will speed up build
  - Nim
