# autogenerated by docgen
# source: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/asyncjs.nim
# rdoccmd: -d:nimExperimentalAsyncjsThen
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/asyncjs_examples_1.nim"
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/asyncjs_examples_2.nim"
