#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim(91, 3)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim", 91, 3).}:
  doAssert big"13" mod big"3" == big"1"
  doAssert big"-13" mod big"3" == big"-1"
  doAssert big"13" mod big"-3" == big"1"
  doAssert big"-13" mod big"-3" == big"-1"

