#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim(61, 3)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim", 61, 3).}:
  doAssert (big("3") + big("2") ** big("66")).wrapToUint(66) == big("3")

