#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim(132, 3)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim", 132, 3).}:
  doAssert (big"555" xor big"2") == big"553"

