#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim(47, 3)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim", 47, 3).}:
  doAssert $big"1024" == "1024n"

