#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim(83, 3)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsbigints.nim", 83, 3).}:
  doAssert big"13" div big"3" == big"4"
  doAssert big"-13" div big"3" == big"-4"
  doAssert big"13" div big"-3" == big"-4"
  doAssert big"-13" div big"-3" == big"4"

