#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsconsole.nim(21, 17)
rdoccmd: -r:off
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsconsole.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsconsole.nim", 21, 17).}:
  console.log "%c My Debug Message", "color: red" # Notice the "%c"
  console.log "%c My Debug %c Message", "color: red", "font-size: 2em"

