# autogenerated by docgen
# source: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsconsole.nim
# rdoccmd: 
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/jsconsole_examples_2.nim"
