#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsffi.nim(224, 3)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsffi.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsffi.nim", 224, 3).}:
  let obj = newJsObject()
  obj.a = 20
  assert obj.a.to(int) == 20

