# autogenerated by docgen
# source: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsffi.nim
# rdoccmd: 
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/jsffi_examples_1.nim"
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/jsffi_examples_2.nim"
