# autogenerated by docgen
# source: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/jsformdata.nim
# rdoccmd: -r:off
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/jsformdata_examples_1.nim"
