#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsre.nim(72, 3)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsre.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsre.nim", 72, 3).}:
  let jsregex: RegExp = newRegExp(r"bcd", r"i")
  assert "abcd".endsWith jsregex

