#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsre.nim(56, 3)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsre.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsre.nim", 56, 3).}:
  let jsregex: RegExp = newRegExp(r"bc$", r"i")
  assert jsregex in r"abc"
  assert jsregex notin r"abcd"
  assert "xabc".contains jsregex

