#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsre.nim(65, 3)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsre.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/js/jsre.nim", 65, 3).}:
  let jsregex: RegExp = newRegExp(r"abc", r"i")
  assert "abcd".startsWith jsregex

