#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim(69, 5)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim", 69, 5).}:
  import std/jsffi
  assert 1.isInteger
  assert not 1.5.isInteger
  assert 1.toJs.isInteger
  assert not 1.5.toJs.isInteger

