#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim(27, 5)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim", 27, 5).}:
  import std/[jsffi, jsbigints]
  assert jsTypeOf(1.toJs) == "number"
  assert jsTypeOf(false.toJs) == "boolean"
  assert [1].toJs.jsTypeOf == "object" # note the difference with `getProtoName`
  assert big"1".toJs.jsTypeOf == "bigint"

