#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim(35, 5)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim", 35, 5).}:
  import std/jsffi
  let a = array[2, float64].default
  assert jsConstructorName(a) == "Float64Array"
  assert jsConstructorName(a.toJs) == "Float64Array"

