# autogenerated by docgen
# source: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim
# rdoccmd: 
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/jsutils_examples_1.nim"
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/jsutils_examples_2.nim"
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/jsutils_examples_3.nim"
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/jsutils_examples_4.nim"
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/jsutils_examples_5.nim"
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/web/upload/1.6.0/nimcache/runnableExamples/jsutils_examples_6.nim"
