#[
autogenerated by docgen
loc: /home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim(64, 3)
rdoccmd: 
]#
import "/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim"
{.line: ("/home/travis/build/nim-lang-cn/website/nim-1.6.0/lib/std/private/jsutils.nim", 64, 3).}:
  let a {.importjs: "Number.MAX_SAFE_INTEGER".}: int64
  assert a == maxSafeInteger

