# Site settings
title: "Nim中文社区"
description: >
  Nim程序设计语言是一种简洁、快速的编程语言，
  可被编译成C、C++甚至JavaScript。
baseurl: ""
official_baseurl: "https://nim-lang.org"

nim_version: 1.0.6

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
      title: "Nim 博客"

navigation:
  - title: 每日早茶
    url: http://tea.nim-cn.com/
  - title: 博客
    url: /blog.html
  - title: 特点
    url: /features.html
  - title: 下载
    url: /install.html
  - title: 学习
    url: /learn.html
  - title: 文档
    url: /documentation.html
  - title: 社区
    url: /community.html
  # - title: 捐赠
  #   url: /donate.html

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
sass:
  style: compressed
exclude:
  - CNAME
  - README.md
  - LICENSE.md

gems:
  - jekyll-asciidoc

asciidoc: {}
asciidoctor:
  attributes:
    - imagesdir=/assets/news/images/asciidoc
    - icons=font
    - source-highlighter=pygments
    - pygments-css=style
